# Kapitel 26: Einstellungen und Messwerte von Uptime Kuma.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false   # Argo CD darf diesen PVC nie löschen
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
