# Die Leiste ganz oben: https://gethomepage.dev/widgets/
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: k3s
    nodes:
      show: false
- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
- search:
    provider: duckduckgo
    target: _blank
