# Kapitel 18: Einstellungen von qBittorrent.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false   # Argo CD darf diesen PVC nie löschen
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
