# Kapitel 20: Einstellungen und Datenbank von sonarr.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false   # Argo CD darf diesen PVC nie löschen
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
